# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4e127500855e8d0ede14eb11fd34cf3b16289fd03c8e5b221bdb3ae12ae3761fa344271d2b8551614a17bfe8631ddda674f47da334b7a302332887e8b1d059

test:
  secret_key_base: bb95116cec1f803fda59954f5439e7c1d9324af003a1337238babc2bbaabe6f8b89b022c1758316de7adf3651c3a3747d1a9b0ee9af8924d5b9e955b073c0987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
